# Generated by Django 4.1.7 on 2023-02-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=50)),
                ('matricula_aluno', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'db_alunos',
            },
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('nome', models.CharField(max_length=40)),
                ('sobrenome', models.CharField(max_length=60)),
                ('disciplina', models.CharField(max_length=30)),
                ('matricula_professor', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'db_professores',
            },
        ),
    ]
