# Generated by Django 4.1.7 on 2023-02-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caderneta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professores',
            name='email_professor',
            field=models.EmailField(default=False, max_length=50),
            preserve_default=False,
        ),
    ]
