# Generated by Django 4.1.7 on 2023-03-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caderneta', '0003_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='nota',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
