# Generated by Django 4.1.7 on 2023-03-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caderneta', '0006_alunos_turmas'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='unidade',
            field=models.CharField(default=100, max_length=15),
            preserve_default=False,
        ),
    ]
