# Generated by Django 4.1.7 on 2023-04-03 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caderneta', '0008_remove_professores_disciplina_turmas_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='professores',
            name='turmas',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='caderneta.turmas'),
            preserve_default=False,
        ),
    ]
