# Generated by Django 4.1.7 on 2023-04-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caderneta', '0009_professores_turmas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='turmas',
            name='disciplina',
        ),
    ]
