# Generated by Django 4.1.7 on 2023-04-03 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caderneta', '0010_disciplinas_remove_turmas_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='professores',
            name='disciplinas',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='caderneta.disciplinas'),
            preserve_default=False,
        ),
    ]
