# Generated by Django 4.1.7 on 2023-04-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caderneta', '0012_alter_notas_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professores',
            name='email_professor',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
