# Generated by Django 4.1.7 on 2023-05-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caderneta', '0013_alter_professores_email_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turmas',
            name='turma',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
