# Generated by Django 4.1.7 on 2023-05-21 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caderneta', '0015_alter_alunos_turmas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='turmas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caderneta.turmas'),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='turma',
            field=models.CharField(max_length=10),
        ),
    ]
